---
id: A705
pairs:
  1 : [02, 01]
  2 : [04, 03]
  3 : [06, 05]
  4 : [08, 07]
  5 : [10, 09]
  6 : [12, 11]
  7 : [14, 13]
  8 : [16, 15]
  9 : [18, 17]
  10: [20, 19]
  11: [22, 21]
  12: [24, 23]
  13: [26, 25]
  14: [28, 27]
  15: [30, 29]
  16: [32, 31]
  17: [34, 33]
  18: [36, 35]
  19: [38, 37]
  20: [40, 39]
  21: [42, 41]
  22: [44, 43]
  23: [46, 45]
  24: [48, 47]
  25: [50, 49]
pairexperts:
  1 : [11, 01]
  2 : [04, 10]
  3 : [15, 05]
  4 : [08, 14]
  5 : [03, 09]
  6 : [12, 02]
  7 : [07, 13]
  8 : [16, 06]
  9 : [27, 17]
  10: [20, 26]
  11: [31, 21]
  12: [24, 30]
  13: [19, 25]
  14: [28, 18]
  15: [23, 29]
  16: [32, 22]
  17: [43, 33]
  18: [36, 42]
  19: [47, 37]
  20: [40, 46]
  21: [35, 41]
  22: [44, 34]
  23: [39, 45]
  24: [48, 38]
  25: [56, 49]
colors:
  1 : #ff0000
  2 : #ff5050
  3 : #ff6600
  4 : #ff9933

  5 : #ffcc00
  6 : #ffff66
  7 : #ccff66
  8 : #99ff66

  9 : #66ff33
  01 : Black
  1-1 : Black
  02 : Blue
  2-1 : Blue
  03 : Brown
  1-2 : Brown
  04 : Gray
  2-2 : Gray
  05 : Green
  2-3 : Green
  11 : BlackBlack
  12 : BlueBlue
  13 : BrownBrown
  14 : GrayGray
  21 : Black
  22 : DarkBlue
  23 : Brown
  24 : GrayGray
  25 : Green
  31 : Orange
  3-1 : Orange
  32 : Pink
  4-1 : Pink
  4-3 : Pink
  33 : Purple
  3-2 : Purple
  3-3 : Yellow
  34 : Red
  4-2 : Red
  4-4 : Red
  35 : White
  41 : OrangeOrange
  42 : PinkPink
  43 : PurplePurple
  44 : Red
  45 : Yellow
  51 : Yellow
  52 : PurplePurple
  53 : Red
  54 : YellowYellow
  61 : OrangeOrange
  62 : PinkPink
  63 : Purple
  13-1 : Orange
  13-2 : Orange
  14-1 : Yellow
  14-2 : Yellow
  # Black     : #333333
  # BlackBlack: #555555
  BlackBlack: Black
  Blue      :
  # BlueBlue  : #3399ff
  BlueBlue  : Blue
  Brown     :
  BrownBrown: #993333
  DarkBlue  :
  DarkGreen :
  Gray      :
  GrayGray  : #f0f0f0
  Green     :
  GreenGreen: #00ff00
  LightBlue :
  LightGreen:
  Orange    :
  Pink      :
  Purple    :
  Red       :
  White     :
  Yellow    :
regions:
  Front:
    - Black
    - Gray
    - Orange
    - Red
  Middle:
    - Brown
    - LightBlue
    - Pink
    - White
  Back:
    - DarkGreen
    - LightGreen
    - Purple
    - Yellow
    - BlackBlack
fourexperts:
  Front:
    A : [08, 07, 16, 15]
    B : [06, 05, 14, 13]
    C : [04, 03, 12, 11]
    D : [02, 01, 10, 09]
  Middle:
    A: [24, 23, 32, 31]
    B: [22, 21, 30, 29]
    C: [20, 19, 28, 27]
    D: [18, 17, 26, 25]
  Back:
    A  : [40, 39, 48, 47]
    B  : [38, 37, 46, 45]
    C  : [36, 35, 44, 43]
    D  : [34, 33, 42, 41]
fours:
  White       : [08, 07, 16, 15]
  Pink        : [06, 05, 14, 13]
  Gray        : [04, 03, 12, 11]
  Black       : [02, 01, 10, 09]

  Yellow      : [24, 23, 32, 31]
  Purple      : [22, 21, 30, 29]
  Green       : [20, 19, 28, 27]
  Blue        : [18, 17, 26, 25]

  YellowYellow: [40, 39, 48, 47]
  Red         : [38, 37, 46, 45]
  Orange      : [36, 35, 44, 43]
  Brown       : [34, 33, 42, 41]

  BlueBlue    : [52, 51, 62, 61]
  BlackBlack  : [50, 49, 60, 64]
threes:
  White       : [08, 07, 16]
  Orange      : [06, 05, 14]
  Green       : [04, 03, 12]
  Black       : [02, 01, 10]

  4-1         : [08, 07, 16]
  3-1         : [06, 05, 14]
  2-1         : [04, 03, 12]
  1-1         : [02, 01, 10]

  Yellow      : [15, 24, 23]
  Pink        : [13, 22, 21]
  Charcoal    : [11, 20, 19]
  Blue        : [09, 18, 17]

  4-2         : [15, 24, 23]
  3-2         : [13, 22, 21]
  2-2         : [11, 20, 19]
  1-2         : [09, 18, 17]

  Silver      : [32, 31, 40]
  Purple      : [30, 29, 38]
  Chocolate   : [28, 27, 36]
  Brown       : [26, 25, 34]

  Violet      : [39, 48, 47]
  Red         : [37, 46, 45]
  Khaki       : [35, 44, 43]
  Gray        : [33, 42, 41]

  4-3         : [32, 31, 40]
  4-4         : [39, 48, 47]
  3-3         : [30, 29, 38]
  3-4         : [37, 46, 45]
  2-3         : [28, 27, 36]
  2-4         : [35, 44, 43]
  1-3         : [26, 25, 34]
  1-4         : [33, 42, 41]

  Golden      : [56,55,54]
  Beige       : [52,51,50]
  Turquoise   : [62,61,60]

  1-5         : [50,49,58]
  1-6         : [57,66,65]
  2-5        : [52,51,60]
  2-6        : [59,68,67]
  3-5        : [54,53,62]
  3-6        : [61,70,69]
  4-5        : [56,55,64]
  4-6        : [63,72,71]

twos:
  01     : [01, 02]
  02     : [03, 04]
  03     : [05, 06]
  04     : [07, 08]
  11     : [09, 10]
  12     : [11, 12]
  13     : [13, 14]
  14     : [15, 16]
  21     : [17, 18]
  22     : [19, 20]
  23     : [21, 22]
  24     : [23, 24]
  31     : [25, 26]
  32     : [27, 28]
  33     : [29, 30]
  34     : [31, 32]
  41     : [33, 34]
  42     : [35, 36]
  43     : [37, 38]
  44     : [39, 40]
  51     : [41, 42]
  52     : [43, 44]
  53     : [45, 46]
  54     : [47, 48]
  61     : [49, 50]
  62     : [51, 52]
  63     : [53, 54]
  64     : [55, 56]
